/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Locacao;
import Model.Pessoa;
import javax.swing.JOptionPane;


/**
 *
 * @author sjcandido
 */
public class FLocacao extends javax.swing.JFrame {
    /**
     * Creates new form Locacao
     */
    public FLocacao() {
        initComponents();
        setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        edDias = new javax.swing.JTextField();
        lbCPF = new javax.swing.JLabel();
        edCpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edTelefone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edEmail = new javax.swing.JTextField();
        opFisica = new javax.swing.JRadioButton();
        opJuridica = new javax.swing.JRadioButton();
        btIncluirVeiculo = new javax.swing.JButton();
        btGerarRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Quantidade dias");

        edDias.setPreferredSize(new java.awt.Dimension(71, 23));

        lbCPF.setText("CPF/CNPJ");

        edCpf.setPreferredSize(new java.awt.Dimension(71, 23));

        jLabel3.setText("Nome");

        edNome.setPreferredSize(new java.awt.Dimension(71, 23));

        jLabel4.setText("Telefone");

        edTelefone.setPreferredSize(new java.awt.Dimension(71, 23));

        jLabel2.setText("e-mail");

        edEmail.setPreferredSize(new java.awt.Dimension(71, 23));

        opFisica.setText("Fisica");

        opJuridica.setText("Juridica");

        btIncluirVeiculo.setText("Incluir Veiculo");
        btIncluirVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirVeiculoActionPerformed(evt);
            }
        });

        btGerarRelatorio.setText("Gerar relatorio");
        btGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(lbCPF)
                            .addComponent(jLabel1))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btIncluirVeiculo)
                            .addGap(34, 34, 34)
                            .addComponent(btGerarRelatorio))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(opFisica)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opJuridica))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCPF)
                    .addComponent(edCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(edNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(edTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(edEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opFisica)
                    .addComponent(opJuridica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIncluirVeiculo)
                    .addComponent(btGerarRelatorio))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btIncluirVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirVeiculoActionPerformed
        int dias = Integer.parseInt(edDias.getText());
        String cpf = edCpf.getText();
        String nome = edNome.getText();
        String telefone = edTelefone.getText();
        String email = edEmail.getText();
        boolean fisica = true; 
        
        if (edCpf.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Valor para o campo CPF está incorreto", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (edNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Valor para o campo NOME está incorreto", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (edTelefone.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Valor para o campo TELEFONE está incorreto", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (edEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Valor para o campo EMAIL está incorreto", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
               
        if (opFisica.isSelected()) {                        
            fisica = true;
        } 
        else if (opJuridica.isSelected()) {
            fisica = false;
           
        } 
        else {
            JOptionPane.showMessageDialog(this, "Valor para o campo TIPO PESSOA está incorreto", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }        
        Pessoa pessoa = new Pessoa(nome, cpf, telefone, email, fisica);
        
        if (dias <= 0) {
            JOptionPane.showMessageDialog(this, "Valor para o campo DIAS DE LOCACAO está incorreto", "Atenção", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        Locacao locacao = new Locacao(dias, pessoa);
        
        JOptionPane.showMessageDialog(this, "Sucesso pessoa inserida", "Suceso", JOptionPane.INFORMATION_MESSAGE);
        
        new FVeiculo().setVisible(true);
    }//GEN-LAST:event_btIncluirVeiculoActionPerformed

    private void btGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarRelatorioActionPerformed
        FRelatorio telaRelatorio = new FRelatorio();
        telaRelatorio.setVisible(true);                
    }//GEN-LAST:event_btGerarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FLocacao().setVisible(true);   
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGerarRelatorio;
    private javax.swing.JButton btIncluirVeiculo;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField edCpf;
    private javax.swing.JTextField edDias;
    private javax.swing.JTextField edEmail;
    private javax.swing.JTextField edNome;
    private javax.swing.JTextField edTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JRadioButton opFisica;
    private javax.swing.JRadioButton opJuridica;
    // End of variables declaration//GEN-END:variables
}
