/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;
import Model.Locacao;
import Model.LocacaoPessoaJuridica;
import Model.Pessoa;
import Model.Veiculo;
import java.util.ArrayList;



/**
 *
 * @author sjcandido
 */
public class FRelatorio extends javax.swing.JPanel {
    private Pessoa pessoa;
    private ArrayList<Veiculo> veiculos;
    private Locacao locacao;
    private LocacaoPessoaJuridica juri;
    
    /**
     * Creates new form Relatorio
     */
    public FRelatorio() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCancela = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taTexto = new javax.swing.JTextArea();

        btCancela.setText("Cancelar");
        btCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelaActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        taTexto.setColumns(20);
        taTexto.setRows(5);
        jScrollPane1.setViewportView(taTexto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btConsultar)
                        .addGap(83, 83, 83)
                        .addComponent(btCancela)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultar)
                    .addComponent(btCancela))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelaActionPerformed
        //this.dispose();
    }//GEN-LAST:event_btCancelaActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        if (pessoa != null) {
            taTexto.setText("Pessoa");             
            taTexto.append("Nome: " + pessoa.getNome() + "\n");
            taTexto.append("CNPJCPF: " + pessoa.getCpfCnpj() + "\n");
            taTexto.append("Telefone: " + pessoa.getTelefone()+ "\n");
            taTexto.append("Email: " + pessoa.getEmail()+ "\n");
            taTexto.setText("----------------------------"+"\n"); 
            taTexto.setText("Locacao");
            taTexto.append("Quantidade Dias: " + locacao.getQuantidadeDias()+ "\n");
            taTexto.append("Valor total: " + locacao.getValorTotal() + "\n");
            taTexto.setText("----------------------------"+"\n");
            taTexto.setText("Informaçao dos veiculos");            
            for (Veiculo veiculos : juri.getVeiculos()) {
                taTexto.append("Placa: " + veiculos.getPlaca() + "\n");
                taTexto.append("KM: " + veiculos.getKM() + "\n");
                taTexto.append("Placa: " + veiculos.getCategoria() + "\n");
                taTexto.append("Preco diaria: " + veiculos.getPrecoDiaria() + "\n");
                taTexto.setText("################################"+"\n");
            }
        } else {
            taTexto.setText("Nenhum item cadastrado.");
        }
    }//GEN-LAST:event_btConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancela;
    private javax.swing.JButton btConsultar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taTexto;
    // End of variables declaration//GEN-END:variables
}
