/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package questao04;

import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;


/**
 *
 * @author Win11
 */
public class AppQuestao4Gui extends javax.swing.JFrame {
    Retangulo04 retangulo = new Retangulo04();
    /**
     * Creates new form AppQuestao4Gui
     */
    public AppQuestao4Gui() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAltura = new javax.swing.JLabel();
        lbComprimento = new javax.swing.JLabel();
        lbPerimetro = new javax.swing.JLabel();
        lbArea = new javax.swing.JLabel();
        btCalcular = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        lbCampoAltura = new javax.swing.JTextField();
        lbCampoComprimento = new javax.swing.JTextField();
        lbResultadoP = new javax.swing.JLabel();
        lbResultadoA = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de retangulos");
        setLocation(new java.awt.Point(0, 0));

        lbAltura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbAltura.setText("Altura:");

        lbComprimento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbComprimento.setText("Comprimento:");

        lbPerimetro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbPerimetro.setText("Perímetro:");

        lbArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbArea.setText("Área:");

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        lbCampoAltura.setColumns(5);
        lbCampoAltura.setForeground(new java.awt.Color(60, 63, 65));
        lbCampoAltura.setName(""); // NOI18N
        lbCampoAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lbCampoAlturaKeyTyped(evt);
            }
        });

        lbCampoComprimento.setColumns(5);
        lbCampoComprimento.setForeground(new java.awt.Color(60, 63, 65));
        lbCampoComprimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lbCampoComprimentoKeyTyped(evt);
            }
        });

        lbResultadoP.setForeground(new java.awt.Color(60, 63, 65));

        lbResultadoA.setForeground(new java.awt.Color(60, 63, 65));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Calculadora de retangulos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbComprimento)
                            .addComponent(lbAltura))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbCampoComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(lbPerimetro))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbCampoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbArea)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbResultadoP, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(lbResultadoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAltura)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbCampoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbResultadoA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComprimento)
                    .addComponent(lbCampoComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPerimetro)
                    .addComponent(lbResultadoP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btCalcular))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed

        int valida = retangulo.setValores(Integer.parseInt(lbCampoAltura.getText()), Integer.parseInt(lbCampoComprimento.getText()));
    
        if ( valida == 0){
            lbResultadoP.setText(String.valueOf(retangulo.calculaPerimetro()));
            lbResultadoA.setText(String.valueOf(retangulo.calculaArea()));  
        }  
        
        
        else{
            switch (valida){
                case 1:
                    JOptionPane.showMessageDialog(null, "Valor incorreto no campo altura");
                    break;
                
                case 2:
                    JOptionPane.showMessageDialog(null, "Valor incorreto no campo comprimento");
                    break;
                    
                case 3:
                    JOptionPane.showMessageDialog(null, "Valor incorreto nos dois campos");
                    break;    
                    
                case 4:
                    JOptionPane.showMessageDialog(null, "Valor zero no campo altura");
                    break;
                    
                case 5:
                    JOptionPane.showMessageDialog(null, "Valor zero no campo comprimento");
                    break;
                    
                case 6:
                    JOptionPane.showMessageDialog(null, "Valor zero nos dois campos");
                    break;
        
                default:     
                    JOptionPane.showMessageDialog(null, "Erro nao tratado");
                    break;
            }
        }       
    }//GEN-LAST:event_btCalcularActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        lbCampoAltura.setText("");
        lbCampoComprimento.setText("");
        lbResultadoA.setText("");
        lbResultadoP.setText("");        
    }//GEN-LAST:event_btLimparActionPerformed

    private void lbCampoAlturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbCampoAlturaKeyTyped
        char caractere = evt.getKeyChar();
    
        if((!Character.isDigit(caractere) && (caractere != KeyEvent.VK_BACK_SPACE) && caractere != KeyEvent.VK_DELETE)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Valor no campo altura nao e um numero");
        } 
    }//GEN-LAST:event_lbCampoAlturaKeyTyped

    private void lbCampoComprimentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbCampoComprimentoKeyTyped
        char caractere = evt.getKeyChar();
    
        if((!Character.isDigit(caractere) && (caractere != KeyEvent.VK_BACK_SPACE) && caractere != KeyEvent.VK_DELETE)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Valor no campo comprimento nao e um numero");
        } 
    }//GEN-LAST:event_lbCampoComprimentoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppQuestao4Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbAltura;
    private javax.swing.JLabel lbArea;
    private javax.swing.JTextField lbCampoAltura;
    private javax.swing.JTextField lbCampoComprimento;
    private javax.swing.JLabel lbComprimento;
    private javax.swing.JLabel lbPerimetro;
    private javax.swing.JLabel lbResultadoA;
    private javax.swing.JLabel lbResultadoP;
    // End of variables declaration//GEN-END:variables
}
