/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.Operacao;
import com.formdev.flatlaf.FlatDarculaLaf;
import javax.swing.*;

/**
 *
 * @author samuel
 */
public class Calculadora extends javax.swing.JFrame {
    Operacao operacao = new Operacao();
    
    private void adicionarNumeroVisor(String numero) {
    String valorMemoria = lbMemoria.getText();
    String valorVisor = lbVisor.getText();
    if (valorVisor.equals("0")) {
        lbVisor.setText(numero);
    } 
    else {
        lbVisor.setText(valorVisor + numero);
    }
}
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbVisor = new javax.swing.JLabel();
        lbMemoria = new javax.swing.JLabel();
        lbOperacoes = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btZero = new javax.swing.JButton();
        btDecimal = new javax.swing.JButton();
        btIgual = new javax.swing.JButton();
        btUm = new javax.swing.JButton();
        btDois = new javax.swing.JButton();
        btTres = new javax.swing.JButton();
        btQuatro = new javax.swing.JButton();
        btCinco = new javax.swing.JButton();
        btMenos = new javax.swing.JButton();
        btSeis = new javax.swing.JButton();
        btMais = new javax.swing.JButton();
        btSete = new javax.swing.JButton();
        btOito = new javax.swing.JButton();
        btNove = new javax.swing.JButton();
        btVezes = new javax.swing.JButton();
        btPorcentagem = new javax.swing.JButton();
        btLimpaUltimoNumero = new javax.swing.JButton();
        btLimpaTudo = new javax.swing.JButton();
        btBackSpace = new javax.swing.JButton();
        btDividido = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(81, 23));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setMaximumSize(new java.awt.Dimension(81, 23));

        lbVisor.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lbVisor.setForeground(new java.awt.Color(255, 255, 255));
        lbVisor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lbMemoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMemoria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lbOperacoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbVisor, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbOperacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                    .addComponent(lbMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbVisor, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(59, 59, 59));
        jButton1.setEnabled(false);
        jButton1.setMaximumSize(new java.awt.Dimension(81, 23));
        jButton1.setOpaque(true);

        btZero.setBackground(new java.awt.Color(59, 59, 59));
        btZero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btZero.setForeground(new java.awt.Color(255, 255, 255));
        btZero.setText("0");
        btZero.setMaximumSize(new java.awt.Dimension(81, 23));
        btZero.setMinimumSize(new java.awt.Dimension(23, 23));
        btZero.setOpaque(true);
        btZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZeroActionPerformed(evt);
            }
        });

        btDecimal.setBackground(new java.awt.Color(59, 59, 59));
        btDecimal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btDecimal.setForeground(new java.awt.Color(255, 255, 255));
        btDecimal.setText(",");
        btDecimal.setMaximumSize(new java.awt.Dimension(81, 23));
        btDecimal.setMinimumSize(new java.awt.Dimension(23, 23));
        btDecimal.setOpaque(true);
        btDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDecimalActionPerformed(evt);
            }
        });

        btIgual.setBackground(new java.awt.Color(109, 169, 216));
        btIgual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btIgual.setForeground(new java.awt.Color(0, 0, 0));
        btIgual.setText("=");
        btIgual.setMaximumSize(new java.awt.Dimension(81, 23));
        btIgual.setMinimumSize(new java.awt.Dimension(23, 23));
        btIgual.setOpaque(true);
        btIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgualActionPerformed(evt);
            }
        });

        btUm.setBackground(new java.awt.Color(59, 59, 59));
        btUm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btUm.setForeground(new java.awt.Color(255, 255, 255));
        btUm.setText("1");
        btUm.setMaximumSize(new java.awt.Dimension(81, 23));
        btUm.setMinimumSize(new java.awt.Dimension(23, 23));
        btUm.setOpaque(true);
        btUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUmActionPerformed(evt);
            }
        });

        btDois.setBackground(new java.awt.Color(59, 59, 59));
        btDois.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btDois.setForeground(new java.awt.Color(255, 255, 255));
        btDois.setText("2");
        btDois.setMaximumSize(new java.awt.Dimension(81, 23));
        btDois.setMinimumSize(new java.awt.Dimension(23, 23));
        btDois.setOpaque(true);
        btDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoisActionPerformed(evt);
            }
        });

        btTres.setBackground(new java.awt.Color(59, 59, 59));
        btTres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btTres.setForeground(new java.awt.Color(255, 255, 255));
        btTres.setText("3");
        btTres.setMaximumSize(new java.awt.Dimension(81, 23));
        btTres.setMinimumSize(new java.awt.Dimension(23, 23));
        btTres.setOpaque(true);
        btTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTresActionPerformed(evt);
            }
        });

        btQuatro.setBackground(new java.awt.Color(59, 59, 59));
        btQuatro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btQuatro.setForeground(new java.awt.Color(255, 255, 255));
        btQuatro.setText("4");
        btQuatro.setMaximumSize(new java.awt.Dimension(81, 23));
        btQuatro.setMinimumSize(new java.awt.Dimension(23, 23));
        btQuatro.setOpaque(true);
        btQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuatroActionPerformed(evt);
            }
        });

        btCinco.setBackground(new java.awt.Color(59, 59, 59));
        btCinco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btCinco.setForeground(new java.awt.Color(255, 255, 255));
        btCinco.setText("5");
        btCinco.setMaximumSize(new java.awt.Dimension(81, 23));
        btCinco.setMinimumSize(new java.awt.Dimension(23, 23));
        btCinco.setOpaque(true);
        btCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCincoActionPerformed(evt);
            }
        });

        btMenos.setBackground(new java.awt.Color(50, 50, 50));
        btMenos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMenos.setForeground(new java.awt.Color(255, 255, 255));
        btMenos.setText("-");
        btMenos.setMinimumSize(new java.awt.Dimension(23, 23));
        btMenos.setOpaque(true);
        btMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenosActionPerformed(evt);
            }
        });

        btSeis.setBackground(new java.awt.Color(59, 59, 59));
        btSeis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btSeis.setForeground(new java.awt.Color(255, 255, 255));
        btSeis.setText("6");
        btSeis.setMinimumSize(new java.awt.Dimension(23, 23));
        btSeis.setOpaque(true);
        btSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeisActionPerformed(evt);
            }
        });

        btMais.setBackground(new java.awt.Color(50, 50, 50));
        btMais.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btMais.setForeground(new java.awt.Color(255, 255, 255));
        btMais.setText("+");
        btMais.setMinimumSize(new java.awt.Dimension(23, 23));
        btMais.setOpaque(true);
        btMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaisActionPerformed(evt);
            }
        });

        btSete.setBackground(new java.awt.Color(59, 59, 59));
        btSete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btSete.setForeground(new java.awt.Color(255, 255, 255));
        btSete.setText("7");
        btSete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSete.setMinimumSize(new java.awt.Dimension(23, 23));
        btSete.setOpaque(true);
        btSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeteActionPerformed(evt);
            }
        });

        btOito.setBackground(new java.awt.Color(59, 59, 59));
        btOito.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btOito.setForeground(new java.awt.Color(255, 255, 255));
        btOito.setText("8");
        btOito.setMinimumSize(new java.awt.Dimension(23, 23));
        btOito.setOpaque(true);
        btOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOitoActionPerformed(evt);
            }
        });

        btNove.setBackground(new java.awt.Color(59, 59, 59));
        btNove.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btNove.setForeground(new java.awt.Color(255, 255, 255));
        btNove.setText("9");
        btNove.setMinimumSize(new java.awt.Dimension(23, 23));
        btNove.setOpaque(true);
        btNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNoveActionPerformed(evt);
            }
        });

        btVezes.setBackground(new java.awt.Color(50, 50, 50));
        btVezes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btVezes.setForeground(new java.awt.Color(255, 255, 255));
        btVezes.setText("X");
        btVezes.setMinimumSize(new java.awt.Dimension(23, 23));
        btVezes.setOpaque(true);
        btVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVezesActionPerformed(evt);
            }
        });

        btPorcentagem.setBackground(new java.awt.Color(50, 50, 50));
        btPorcentagem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btPorcentagem.setForeground(new java.awt.Color(255, 255, 255));
        btPorcentagem.setText("%");
        btPorcentagem.setMinimumSize(new java.awt.Dimension(23, 23));
        btPorcentagem.setOpaque(true);
        btPorcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPorcentagemActionPerformed(evt);
            }
        });

        btLimpaUltimoNumero.setBackground(new java.awt.Color(50, 50, 50));
        btLimpaUltimoNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btLimpaUltimoNumero.setForeground(new java.awt.Color(255, 255, 255));
        btLimpaUltimoNumero.setText("CE");
        btLimpaUltimoNumero.setMinimumSize(new java.awt.Dimension(72, 23));
        btLimpaUltimoNumero.setOpaque(true);
        btLimpaUltimoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpaUltimoNumeroActionPerformed(evt);
            }
        });

        btLimpaTudo.setBackground(new java.awt.Color(50, 50, 50));
        btLimpaTudo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btLimpaTudo.setForeground(new java.awt.Color(255, 255, 255));
        btLimpaTudo.setText("C");
        btLimpaTudo.setMinimumSize(new java.awt.Dimension(23, 23));
        btLimpaTudo.setOpaque(true);
        btLimpaTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpaTudoActionPerformed(evt);
            }
        });

        btBackSpace.setBackground(new java.awt.Color(50, 50, 50));
        btBackSpace.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btBackSpace.setForeground(new java.awt.Color(255, 255, 255));
        btBackSpace.setText("<=");
        btBackSpace.setMinimumSize(new java.awt.Dimension(72, 23));
        btBackSpace.setOpaque(true);
        btBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackSpaceActionPerformed(evt);
            }
        });

        btDividido.setBackground(new java.awt.Color(50, 50, 50));
        btDividido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btDividido.setForeground(new java.awt.Color(255, 255, 255));
        btDividido.setText("÷");
        btDividido.setMinimumSize(new java.awt.Dimension(72, 23));
        btDividido.setOpaque(true);
        btDividido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDivididoActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(50, 50, 50));
        jButton22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setEnabled(false);
        jButton22.setMinimumSize(new java.awt.Dimension(23, 23));
        jButton22.setOpaque(true);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(50, 50, 50));
        jButton23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setEnabled(false);
        jButton23.setMinimumSize(new java.awt.Dimension(72, 23));
        jButton23.setOpaque(true);

        jButton24.setBackground(new java.awt.Color(50, 50, 50));
        jButton24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setEnabled(false);
        jButton24.setMinimumSize(new java.awt.Dimension(23, 23));
        jButton24.setOpaque(true);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimpaUltimoNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btZero, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btSete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btOito, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btUm, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btCinco, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(btDois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(btSeis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btTres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btNove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btLimpaTudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btDividido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btVezes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btMenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btMais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btLimpaUltimoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBackSpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btPorcentagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btLimpaTudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btDividido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jButton22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btOito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btNove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btVezes, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btQuatro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btMenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMais, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUmActionPerformed
        adicionarNumeroVisor("1");
    }//GEN-LAST:event_btUmActionPerformed

    private void btDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoisActionPerformed
        adicionarNumeroVisor("2");
    }//GEN-LAST:event_btDoisActionPerformed

    private void btTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTresActionPerformed
        adicionarNumeroVisor("3");
    }//GEN-LAST:event_btTresActionPerformed

    private void btQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuatroActionPerformed
        adicionarNumeroVisor("4");
    }//GEN-LAST:event_btQuatroActionPerformed

    private void btCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCincoActionPerformed
        adicionarNumeroVisor("5");
    }//GEN-LAST:event_btCincoActionPerformed

    private void btSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeisActionPerformed
        adicionarNumeroVisor("6");
    }//GEN-LAST:event_btSeisActionPerformed

    private void btSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeteActionPerformed
        adicionarNumeroVisor("7");
    }//GEN-LAST:event_btSeteActionPerformed

    private void btOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOitoActionPerformed
        adicionarNumeroVisor("8");
    }//GEN-LAST:event_btOitoActionPerformed

    private void btNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNoveActionPerformed
        adicionarNumeroVisor("9");
    }//GEN-LAST:event_btNoveActionPerformed

    private void btMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaisActionPerformed
            // Se o visor está vazio, não faça nada
            if (lbVisor.getText().isEmpty()) {
                return;
            }
            
            double valorVisor = Double.parseDouble(lbVisor.getText());
            double  valorMemoria = lbMemoria.getText().isEmpty() ? 0.0 : Double.parseDouble(lbMemoria.getText());

            operacao.setNumA(valorMemoria);
            operacao.setNumB(valorVisor);

            double resultado = operacao.mais();

            lbMemoria.setText(Double.toString(resultado));
            lbVisor.setText("0");
            lbOperacoes.setText("+");        
    }//GEN-LAST:event_btMaisActionPerformed

    private void btMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenosActionPerformed
            // Se o visor está vazio, não faça nada
            if (lbVisor.getText().isEmpty()) {
                return;
            }
            
            double valorVisor = Double.parseDouble(lbVisor.getText());
            double  valorMemoria = lbMemoria.getText().isEmpty() ? 0.0 : Double.parseDouble(lbMemoria.getText());

            operacao.setNumA(valorMemoria);
            operacao.setNumB(valorVisor);

            double resultado = operacao.menos();

            lbMemoria.setText(Double.toString(resultado));
            lbVisor.setText("0");
            lbOperacoes.setText("-");  
    }//GEN-LAST:event_btMenosActionPerformed

    private void btVezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVezesActionPerformed
            // Se o visor está vazio, não faça nada
            if (lbVisor.getText().isEmpty()) {
                return;
            }
            
            double valorVisor = Double.parseDouble(lbVisor.getText());
            double  valorMemoria = lbMemoria.getText().isEmpty() ? 0.0 : Double.parseDouble(lbMemoria.getText());

            operacao.setNumA(valorMemoria);
            operacao.setNumB(valorVisor);
            
            double resultado = operacao.vezes();
            
            if (resultado == 0){
                valorMemoria = valorVisor;
                lbMemoria.setText(Double.toString(valorMemoria));
            }
            else{
                lbMemoria.setText(Double.toString(resultado));
            }

            lbVisor.setText("0");
            lbOperacoes.setText("*");  
    }//GEN-LAST:event_btVezesActionPerformed

    private void btDivididoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDivididoActionPerformed
            // Se o visor está vazio, não faça nada
            if (lbVisor.getText().isEmpty()) {
                return;
            }
            
            double valorVisor = Double.parseDouble(lbVisor.getText());
            double  valorMemoria = lbMemoria.getText().isEmpty() ? 0.0 : Double.parseDouble(lbMemoria.getText());

            operacao.setNumA(valorMemoria);
            operacao.setNumB(valorVisor);
            
            double resultado = operacao.dividido();
            
            if (resultado == 0){
                valorMemoria = valorVisor;
                lbMemoria.setText(Double.toString(valorMemoria));
            }
            else{
                lbMemoria.setText(Double.toString(resultado));
            }

            lbVisor.setText("0");
            lbOperacoes.setText("/");  

    }//GEN-LAST:event_btDivididoActionPerformed

    private void btBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackSpaceActionPerformed
        String numeroAtual = lbVisor.getText();

        if (numeroAtual.length() > 1) {
            numeroAtual = numeroAtual.substring(0, numeroAtual.length() - 1);
        } 
        
        else {
            numeroAtual = "0";
        }

        lbVisor.setText(numeroAtual);
    }//GEN-LAST:event_btBackSpaceActionPerformed

    private void btLimpaTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpaTudoActionPerformed
        lbVisor.setText("0");
        lbMemoria.setText("");
        lbOperacoes.setText("");
        operacao.setNumA(0.0);
        operacao.setNumB(0.0);
    }//GEN-LAST:event_btLimpaTudoActionPerformed

    private void btLimpaUltimoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpaUltimoNumeroActionPerformed
        lbVisor.setText("0");
    }//GEN-LAST:event_btLimpaUltimoNumeroActionPerformed

    private void btPorcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPorcentagemActionPerformed
        double numeroAtual = Double.parseDouble(lbVisor.getText());
        double numeroPorcentagem = Double.parseDouble(lbMemoria.getText());
        double resultado = operacao.porcentagem(numeroAtual, numeroPorcentagem);
        lbVisor.setText(String.valueOf(resultado));
        lbMemoria.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btPorcentagemActionPerformed

    private void btDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDecimalActionPerformed
        double numeroAtual = Double.parseDouble(lbVisor.getText());
        lbVisor.setText(String.valueOf(numeroAtual));
    }//GEN-LAST:event_btDecimalActionPerformed

    private void btZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZeroActionPerformed
        adicionarNumeroVisor("0");      
    }//GEN-LAST:event_btZeroActionPerformed

    private void btIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgualActionPerformed
        if (lbVisor.getText().isEmpty()) {
            return;
        }
        operacao.setNumA(Double.parseDouble(lbMemoria.getText()));
        operacao.setNumB(Double.parseDouble(lbVisor.getText()));
        
        realizarOperacao(lbOperacoes.getText());

    }//GEN-LAST:event_btIgualActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here: talvez colocar cursor
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here: talvez colocar cursor
    }//GEN-LAST:event_jButton24ActionPerformed
    
     private void realizarOperacao(String operador) {
    double resultado = 0.0;

    switch (operador) {
        case "+":
            resultado = operacao.mais();
            break;
        case "-":
            resultado = operacao.menos();
            break;
        case "*":
            resultado = operacao.vezes();
            
            break;
        case "/":
            if (operacao.getNumB() != 0) {
                resultado = operacao.dividido();
            } else {
                JOptionPane.showMessageDialog(null, "Divisão por zero não permitida!");
                return;
            }
            break;
        default:
            JOptionPane.showMessageDialog(null, "Operação inválida!");
            return;
    }

    lbMemoria.setText(Double.toString(resultado));
    lbVisor.setText(Double.toString(resultado));
}   
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        SwingUtilities.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(new FlatDarculaLaf());
                
                JFrame frame = new JFrame("Calculadora");           
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                
                frame.setVisible(true);
            } 
            catch (Exception e) {
                e.printStackTrace();
            }
        });
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    static javax.swing.JButton btBackSpace;
    static javax.swing.JButton btCinco;
    static javax.swing.JButton btDecimal;
    static javax.swing.JButton btDividido;
    static javax.swing.JButton btDois;
    static javax.swing.JButton btIgual;
    static javax.swing.JButton btLimpaTudo;
    static javax.swing.JButton btLimpaUltimoNumero;
    static javax.swing.JButton btMais;
    static javax.swing.JButton btMenos;
    static javax.swing.JButton btNove;
    static javax.swing.JButton btOito;
    static javax.swing.JButton btPorcentagem;
    static javax.swing.JButton btQuatro;
    static javax.swing.JButton btSeis;
    static javax.swing.JButton btSete;
    static javax.swing.JButton btTres;
    static javax.swing.JButton btUm;
    static javax.swing.JButton btVezes;
    static javax.swing.JButton btZero;
    static javax.swing.JButton jButton1;
    static javax.swing.JButton jButton22;
    static javax.swing.JButton jButton23;
    static javax.swing.JButton jButton24;
    static javax.swing.JPanel jPanel1;
    static javax.swing.JPanel jPanel2;
    static javax.swing.JLabel lbMemoria;
    static javax.swing.JLabel lbOperacoes;
    static javax.swing.JLabel lbVisor;
    // End of variables declaration//GEN-END:variables
}
